'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
'
Namespace FileService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="EquipmentFileServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EquipmentFileService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetFileByteStreamFromDCOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetFileInfoFromDCOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateTransferStatusOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ErrorMessageOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetBillerLogoFileOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteBillerLogoFileOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.KioskPayment.My.MySettings.Default.KioskPayment_FileService_EquipmentFileService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetFileByteStreamFromDCCompleted As GetFileByteStreamFromDCCompletedEventHandler
        
        '''<remarks/>
        Public Event GetFileInfoFromDCCompleted As GetFileInfoFromDCCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateTransferStatusCompleted As UpdateTransferStatusCompletedEventHandler
        
        '''<remarks/>
        Public Event ErrorMessageCompleted As ErrorMessageCompletedEventHandler
        
        '''<remarks/>
        Public Event GetBillerLogoFileCompleted As GetBillerLogoFileCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteBillerLogoFileCompleted As DeleteBillerLogoFileCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFileByteStreamFromDC", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetFileByteStreamFromDC(ByVal FilePath As String) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("GetFileByteStreamFromDC", New Object() {FilePath})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetFileByteStreamFromDCAsync(ByVal FilePath As String)
            Me.GetFileByteStreamFromDCAsync(FilePath, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetFileByteStreamFromDCAsync(ByVal FilePath As String, ByVal userState As Object)
            If (Me.GetFileByteStreamFromDCOperationCompleted Is Nothing) Then
                Me.GetFileByteStreamFromDCOperationCompleted = AddressOf Me.OnGetFileByteStreamFromDCOperationCompleted
            End If
            Me.InvokeAsync("GetFileByteStreamFromDC", New Object() {FilePath}, Me.GetFileByteStreamFromDCOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetFileByteStreamFromDCOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetFileByteStreamFromDCCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetFileByteStreamFromDCCompleted(Me, New GetFileByteStreamFromDCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFileInfoFromDC", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetFileInfoFromDC(ByVal EventDate As String, ByVal ShopAbb As String, ByVal TargetType As String) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("GetFileInfoFromDC", New Object() {EventDate, ShopAbb, TargetType})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetFileInfoFromDCAsync(ByVal EventDate As String, ByVal ShopAbb As String, ByVal TargetType As String)
            Me.GetFileInfoFromDCAsync(EventDate, ShopAbb, TargetType, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetFileInfoFromDCAsync(ByVal EventDate As String, ByVal ShopAbb As String, ByVal TargetType As String, ByVal userState As Object)
            If (Me.GetFileInfoFromDCOperationCompleted Is Nothing) Then
                Me.GetFileInfoFromDCOperationCompleted = AddressOf Me.OnGetFileInfoFromDCOperationCompleted
            End If
            Me.InvokeAsync("GetFileInfoFromDC", New Object() {EventDate, ShopAbb, TargetType}, Me.GetFileInfoFromDCOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetFileInfoFromDCOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetFileInfoFromDCCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetFileInfoFromDCCompleted(Me, New GetFileInfoFromDCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateTransferStatus", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateTransferStatus(ByVal FileScheduleID As String) As Boolean
            Dim results() As Object = Me.Invoke("UpdateTransferStatus", New Object() {FileScheduleID})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UpdateTransferStatusAsync(ByVal FileScheduleID As String)
            Me.UpdateTransferStatusAsync(FileScheduleID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateTransferStatusAsync(ByVal FileScheduleID As String, ByVal userState As Object)
            If (Me.UpdateTransferStatusOperationCompleted Is Nothing) Then
                Me.UpdateTransferStatusOperationCompleted = AddressOf Me.OnUpdateTransferStatusOperationCompleted
            End If
            Me.InvokeAsync("UpdateTransferStatus", New Object() {FileScheduleID}, Me.UpdateTransferStatusOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateTransferStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateTransferStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateTransferStatusCompleted(Me, New UpdateTransferStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ErrorMessage", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ErrorMessage() As String
            Dim results() As Object = Me.Invoke("ErrorMessage", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ErrorMessageAsync()
            Me.ErrorMessageAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ErrorMessageAsync(ByVal userState As Object)
            If (Me.ErrorMessageOperationCompleted Is Nothing) Then
                Me.ErrorMessageOperationCompleted = AddressOf Me.OnErrorMessageOperationCompleted
            End If
            Me.InvokeAsync("ErrorMessage", New Object(-1) {}, Me.ErrorMessageOperationCompleted, userState)
        End Sub
        
        Private Sub OnErrorMessageOperationCompleted(ByVal arg As Object)
            If (Not (Me.ErrorMessageCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ErrorMessageCompleted(Me, New ErrorMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBillerLogoFile", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetBillerLogoFile() As System.Data.DataTable
            Dim results() As Object = Me.Invoke("GetBillerLogoFile", New Object(-1) {})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetBillerLogoFileAsync()
            Me.GetBillerLogoFileAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetBillerLogoFileAsync(ByVal userState As Object)
            If (Me.GetBillerLogoFileOperationCompleted Is Nothing) Then
                Me.GetBillerLogoFileOperationCompleted = AddressOf Me.OnGetBillerLogoFileOperationCompleted
            End If
            Me.InvokeAsync("GetBillerLogoFile", New Object(-1) {}, Me.GetBillerLogoFileOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetBillerLogoFileOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetBillerLogoFileCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetBillerLogoFileCompleted(Me, New GetBillerLogoFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteBillerLogoFile", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DeleteBillerLogoFile(ByVal FileName As String) As Boolean
            Dim results() As Object = Me.Invoke("DeleteBillerLogoFile", New Object() {FileName})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DeleteBillerLogoFileAsync(ByVal FileName As String)
            Me.DeleteBillerLogoFileAsync(FileName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteBillerLogoFileAsync(ByVal FileName As String, ByVal userState As Object)
            If (Me.DeleteBillerLogoFileOperationCompleted Is Nothing) Then
                Me.DeleteBillerLogoFileOperationCompleted = AddressOf Me.OnDeleteBillerLogoFileOperationCompleted
            End If
            Me.InvokeAsync("DeleteBillerLogoFile", New Object() {FileName}, Me.DeleteBillerLogoFileOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteBillerLogoFileOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteBillerLogoFileCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteBillerLogoFileCompleted(Me, New DeleteBillerLogoFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub GetFileByteStreamFromDCCompletedEventHandler(ByVal sender As Object, ByVal e As GetFileByteStreamFromDCCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetFileByteStreamFromDCCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub GetFileInfoFromDCCompletedEventHandler(ByVal sender As Object, ByVal e As GetFileInfoFromDCCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetFileInfoFromDCCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub UpdateTransferStatusCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateTransferStatusCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateTransferStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub ErrorMessageCompletedEventHandler(ByVal sender As Object, ByVal e As ErrorMessageCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ErrorMessageCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub GetBillerLogoFileCompletedEventHandler(ByVal sender As Object, ByVal e As GetBillerLogoFileCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetBillerLogoFileCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub DeleteBillerLogoFileCompletedEventHandler(ByVal sender As Object, ByVal e As DeleteBillerLogoFileCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DeleteBillerLogoFileCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
End Namespace
